Repository kuopii/lms-frontend, pull requests merged in 2025-08, with the labels that each got.

#20 feat: add question templates and types for various question formats
  app/dashboard/listening/page.tsx
  app/dashboard/overview-page/[id]/page.tsx
  app/dashboard/reading/page.tsx
  app/dashboard/speaking/page.tsx
  app/dashboard/test/listening/create/page.tsx
  app/dashboard/test/page.tsx
  app/dashboard/vocabulary/page.tsx
  app/dashboard/writing/page.tsx
  components/card-dashboard/CardDashboard.tsx
  components/ui/button.tsx
  components/ui/line-charts.tsx
  components/ui/switch.tsx
  data/dummy-data-listening.ts
  features/dashboard/dashboard-listening/components/answer-key-dialog.tsx
  features/dashboard/dashboard-listening/components/audio-dropzone.tsx
  features/dashboard/dashboard-listening/components/error-form.tsx
  features/dashboard/dashboard-listening/components/image-dropzone.tsx
  features/dashboard/dashboard-listening/components/question-per-section.tsx
  features/dashboard/dashboard-listening/components/question-renderer.tsx
  features/dashboard/dashboard-listening/components/sortable-question.tsx
  features/dashboard/dashboard-listening/components/templates-questions/choose-multiple-answers.tsx
  features/dashboard/dashboard-listening/components/templates-questions/choose-the-correct-answer.tsx
  features/dashboard/dashboard-listening/components/templates-questions/form-completion.tsx
  features/dashboard/dashboard-listening/components/templates-questions/map-labeling.tsx
  features/dashboard/dashboard-listening/components/templates-questions/note-completion.tsx
  features/dashboard/dashboard-listening/components/templates-questions/sentence-completion.tsx
  features/dashboard/dashboard-listening/components/templates-questions/short-answer-question.tsx
  features/dashboard/dashboard-listening/components/templates-questions/summary-completion.tsx
  features/dashboard/dashboard-listening/components/transcript/speaker-inputs.tsx
  features/dashboard/dashboard-listening/components/transcript/transcript-conversation.tsx
  features/dashboard/dashboard-listening/components/transcript/transcript-descriptive.tsx
  features/dashboard/dashboard-listening/components/transcript/transcript-form.tsx
  features/dashboard/dashboard-listening/types/question-templates.ts
  features/dashboard/dashboard-listening/types/question.ts
  features/dashboard/dashboard-listening/utils/arrray-equal.ts
  features/dashboard/dashboard-listening/utils/handle-drag-end.ts
  features/dashboard/dashboard-listening/utils/is-array.ts
  features/dashboard/dashboard-listening/utils/is-object.ts
  features/dashboard/dashboard-listening/utils/parsed-fields.ts
  package-lock.json
  package.json
  public/icons/lamp.png
  validators/create-test-listening-teacher.ts
Labels: enhancement

#21 Implement create listening and reading test pages with form handling and validation
  app/test/layout.tsx
  app/test/listening/create/page.tsx
  app/test/reading/create/page.tsx
  features/test/reading/components/base-form.tsx
  features/test/reading/form/create-listening-form.ts
  features/test/reading/form/create-reading-form.ts
  features/test/reading/pages/create-listening-test.tsx
  features/test/reading/pages/create-reading-test.tsx
  features/test/reading/pages/create-test-page.tsx
  store/form-store.ts
  validators/test.ts
Labels: bug, duplicate, enhancement

#22 Refactor test creation forms and related components
  app/test/listening/create/page.tsx
  app/test/reading/create/page.tsx
  features/test/components/base-form.tsx
  features/test/constant/default-question-values.ts
  features/test/form/create-listening-form.ts
  features/test/form/create-reading-form.ts
  features/test/pages/create-listening-test.tsx
  features/test/pages/create-reading-test.tsx
  features/test/reading/components/passage-section.tsx
  features/test/reading/components/questions-section.tsx
  features/test/reading/components/questions/matching-information.tsx
  helpers/format-time-label.ts
  helpers/index-to-letter.ts
Labels: duplicate, good first issue

#25 refactor(test-form): rename fields, simplify schema, and update UI integration
  app/test/layout.tsx
  features/test/components/base-form.tsx
  features/test/form/create-listening-form.ts
  features/test/form/create-reading-form.ts
  features/test/pages/create-listening-test.tsx
  features/test/pages/create-reading-test.tsx
  types/test.ts
  validators/test.ts
Labels: bug, good first issue

#29 Fixing answer key 22ags
  features/test/components/answer-key-field.tsx
  features/test/components/options-field-array.tsx
  features/test/components/questions/choose-correct-answer.tsx
  features/test/components/questions/choose-multiple-answer.tsx
  features/test/components/questions/true-false-not-given.tsx
  features/test/components/questions/yes-no-not-given.tsx
  features/test/pages/create-listening-test.tsx
Labels: bug, enhancement

#30 Fix-question-breakdown
  app/dashboard/vocabulary/page.tsx
  app/globals.css
  components/ui/badge.tsx
  features/dashboard/vocabulary/api/use-create-vocabulary.ts
  features/dashboard/vocabulary/api/use-fetch-vocabularies.ts
  features/dashboard/vocabulary/api/use-update-vocabulary.ts
  features/dashboard/vocabulary/components/card-vocabulary.tsx
  features/dashboard/vocabulary/components/vocabulary-modal.tsx
  features/dashboard/vocabulary/pages/vocabulary-page.tsx
  features/test/components/question-breakdown.tsx
  features/test/components/question-header.tsx
  features/test/components/questions/choose-correct-answer.tsx
  features/test/components/questions/choose-multiple-answer.tsx
  features/test/components/questions/true-false-not-given.tsx
  features/test/components/questions/yes-no-not-given.tsx
  features/test/constant/default-reading-question.ts
  features/test/form/create-reading-form.ts
  features/test/pages/create-reading-test.tsx
  package-lock.json
  package.json
  store/vocab-store.ts
Labels: bug, enhancement

#31 Fix-toolbar
  features/test/components/question-image.tsx
  features/test/components/questions/choose-correct-answer.tsx
  features/test/components/questions/choose-multiple-answer.tsx
  features/test/components/questions/true-false-not-given.tsx
  features/test/components/questions/yes-no-not-given.tsx
  features/test/components/toolbar.tsx
  features/test/form/create-listening-form.ts
  features/test/form/create-reading-form.ts
  features/test/listening/components/passage-section.tsx
  features/test/listening/components/questions-section.tsx
  features/test/reading/components/questions-section.tsx
Labels: bug, enhancement

#32 Fix points value
  components/ui/badge.tsx
  data/test-filter-options.ts
  features/test/components/points-field.tsx
  features/test/components/questions/choose-correct-answer.tsx
  features/test/components/questions/choose-multiple-answer.tsx
  features/test/components/questions/true-false-not-given.tsx
  features/test/components/questions/yes-no-not-given.tsx
  features/test/form/create-listening-form.ts
  features/test/form/create-reading-form.ts
  features/test/pages/create-listening-test.tsx
  features/test/pages/create-reading-test.tsx
  features/test/reading/components/answer-key-field.tsx
  features/test/reading/components/options-field-array.tsx
  features/test/reading/components/question-header.tsx
  helpers/flattern-error.ts
  helpers/index-to-letter.ts
  hooks/use-points-calculation.ts
  types/test.ts
Labels: bug, duplicate, enhancement
